# Generated by Django 2.1 on 2019-08-01 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_s3_storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_file', models.FileField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-185x73fds'), upload_to='')),
                ('file_desc', models.TextField(blank=True)),
                ('file_downloader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_downloader', to=settings.AUTH_USER_MODEL)),
                ('file_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
