# Generated by Django 2.1 on 2019-08-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='file_name',
            field=models.CharField(default='file_test', max_length=20),
        ),
    ]
